# Generated by Django 3.2.5 on 2021-07-29 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_auto_20210729_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, size=None),
        ),
    ]
